name: CI

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run before
        run: ./before-script
      - name: Pre deploy test install
        run: ./install
  deploy_updates:
    runs-on: ubuntu-latest
    needs: [build_and_test]
    steps:
      - uses: actions/checkout@v1
      - name: Run before
        run: ./before-script
      - name: Deploy updates and test 
        run: ./update
