name: CI

on: [push]

jobs:
  build and test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Run before
        run: ./before-script
      - name: Pre deploy test install
        run: ./install
  deploy updates:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Run before
        run: ./before-script
      - name: Deploy updates and test 
        run: ./update
